manifest:
  defaults:
    #revision: v0.3.0
    revision: main
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: zmkfirmware-hidbattery
      url-base: https://github.com/Genteure
    - name: urob
      url-base: https://github.com/urob
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
    - name: sch3fr
      url-base: https://github.com/sch3fr
    - name: charlesmst
      url-base: https://github.com/charlesmst
    - name: englmaxi
      url-base: https://github.com/englmaxi
    - name: darukutsu
      #url-base: https://github.com/darukutsu
      url-base: ""
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    #- name: zmk
    #  remote: zmkfirmware-hidbattery
    #  import: app/west.yml
    #  revision: feat/battery-reporting
    #- name: zmk
    #  remote: petejohanson
    #  import: app/west.yml
    #  revision: core/move-to-zephyr-4-1
    - name: zmk-helpers
      remote: urob
      path: modules/zmk/zmk-helpers
    - name: zmk-unicode
      remote: urob
      path: modules/zmk/zmk-unicode
    - name: zmk-dongle-display
      remote: englmaxi
      path: modules/zmk/zmk-dongle-display
      revision: main
    - name: zmk-dongle-display-view
      remote: mctechnology17
      path: modules/zmk/zmk-dongle-display-view
      revision: main
    # check once fixed for 4.1 release
    #- name: zmk-config
    #  remote: mctechnology17
    #  path: modules/zmk/zmk-config
    #  revision: main
    - name: zmk-config-unix60
      remote: sch3fr
      path: modules/zmk/zmk-config-unix60
      revision: master
    - name: nrf52840-dongle
      remote: darukutsu
      path: modules/zmk/nrf52840-dongle
      revision: main
    # check once fixed for 4.1 release
    - name: zephyr-ble-hid-usb-translator
      remote: charlesmst
      path: modules/zmk/zephyr-ble-hid-usb-translator
      revision: main
  self:
    path: config
