#name: searxng
services:
  app:
    container_name: searxng
    image: searxng/searxng
    ports:
      - 8080:8080
    volumes:
      - ./searxng:/etc/searxng
    environment:
      #BASE_URL: http://localhost:8080/
      INSTANCE_NAME: daru-localhost-instance
    restart: unless-stopped
