#name: searxng
services:
  app:
    container_name: searxng
    image: searxng/searxng
    ports:
      - 8080:8080
    volumes:
      - ./searxng:/etc/searxng
    environment:
      SEARXNG_BASE_URL: http://localhost:8080/
      SEARXNG_SECRET:
      SEARXNG_PUBLIC_INSTANCE: false
      SEARXNG_LIMITER: false
      SEARXNG_IMAGE_PROXY: true
    restart: unless-stopped
