layout: {zmk_keyboard: corne}
layers:
  COL:
  - {t: '$$phosphor:regular/arrows-left-right$$', h: Tab}
  - Q
  - W
  - F
  - P
  - B
  - J
  - L
  - U
  - Y
  - ;
  - $$phosphor:regular/backspace$$
  - ESC
  - A
  - R
  - S
  - {t: T, h: '$$mdi:apple-keyboard-control$$'}
  - G
  - M
  - N
  - E
  - I
  - O
  - ''''
  - {t: '$$phosphor:regular/arrow-fat-lines-up$$', h: SftCaps}
  - {t: Z, h: '$$fa:brands/linux$$ LGui'}
  - X
  - C
  - D
  - V
  - K
  - H
  - ','
  - .
  - {t: /, h: '$$fa:brands/linux$$ LGui'}
  - {t: '$$phosphor:regular/key-return$$', h: RSHIFT}
  - {t: SK, h: '$$fa:brands/linux$$ LGui'}
  - {t: '[', h: VIM}
  - {t: '$$mdi:keyboard-space$$', h: '$$mdi:apple-keyboard-option$$'}
  - {t: '$$mdi:infinity$$', h: Meh}
  - {t: ']', h: PROG}
  - {t: '$$phosphor:regular/repeat$$', h: Repeat}
  COLZY:
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - Z
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: Y, h: '$$fa:brands/linux$$ LGui'}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  QWERTY:
  - {t: '$$phosphor:regular/arrows-left-right$$', h: Tab}
  - Q
  - W
  - E
  - R
  - T
  - Y
  - U
  - I
  - O
  - P
  - $$phosphor:regular/backspace$$
  - {t: '$$phosphor:regular/arrow-fat-up$$', h: LSft}
  - A
  - S
  - D
  - F
  - G
  - H
  - J
  - K
  - L
  - ;
  - ''''
  - {t: '$$mdi:apple-keyboard-control$$', h: LCtl}
  - Z
  - X
  - C
  - V
  - B
  - N
  - M
  - ','
  - .
  - /
  - {t: '$$phosphor:regular/key-return$$', h: RSHIFT}
  - ESC
  - {t: '$$mdi:apple-keyboard-option$$', h: LAlt}
  - {t: '$$mdi:keyboard-space$$', h: Spc}
  - {t: '[', h: VIM}
  - {t: ']', h: PROG}
  - {t: '$$mdi:apple-keyboard-option$$', h: RAlt}
  GAM1:
  - {t: '$$phosphor:regular/arrows-left-right$$', h: Tab}
  - Q
  - W
  - E
  - R
  - T
  - Y
  - U
  - I
  - O
  - P
  - $$phosphor:regular/backspace$$
  - {t: '$$phosphor:regular/arrow-fat-up$$', h: LSft}
  - A
  - S
  - D
  - F
  - G
  - H
  - J
  - K
  - L
  - ;
  - ''''
  - {t: '$$mdi:apple-keyboard-control$$', h: LCtl}
  - Z
  - X
  - C
  - V
  - B
  - N
  - M
  - ','
  - .
  - /
  - {t: '$$phosphor:regular/key-return$$', h: Ret}
  - {t: '$$mdi:apple-keyboard-option$$', h: LAlt}
  - {t: ESC, h: GAM2}
  - {t: '$$mdi:keyboard-space$$', h: Spc}
  - {t: '[', h: VIM}
  - {t: ']', h: PROG}
  - {t: '$$mdi:apple-keyboard-option$$', h: RAlt}
  GAM2:
  - {t: GAM3, h: toggle}
  - '1'
  - {t: ▽, type: trans}
  - '2'
  - '3'
  - '4'
  - F1
  - F2
  - F3
  - F4
  - F5
  - {t: ▽, type: trans}
  - {t: GAM4, h: toggle}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '5'
  - '6'
  - F6
  - F7
  - F8
  - F9
  - F10
  - {t: ▽, type: trans}
  - ESC
  - '7'
  - '8'
  - '9'
  - '0'
  - '='
  - F11
  - F12
  - ''
  - F11
  - F12
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  GAM3:
  - {t: GAM3, h: toggle}
  - F1
  - F2
  - F3
  - F4
  - F5
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - F6
  - F7
  - F8
  - F9
  - F10
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - F11
  - F12
  - ''
  - F11
  - F12
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  GAM4:
  - {t: ▽, type: trans}
  - '!'
  - '@'
  - '#'
  - $
  - '%'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: GAM4, h: toggle}
  - ^
  - '&'
  - '*'
  - (
  - )
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '7'
  - '8'
  - '9'
  - '0'
  - '='
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  VIM:
  - F1
  - F2
  - F3
  - F4
  - F5
  - F6
  - F7
  - F8
  - F9
  - F10
  - F11
  - F12
  - ESC
  - INS
  - PSCRN
  - +PSCRN
  - {t: '$$phosphor:regular/caret-double-down$$', h: PgDn}
  - {t: '$$phosphor:regular/caret-double-up$$', h: PgUp}
  - {t: '$$phosphor:regular/arrow-left$$', h: Left}
  - {t: '$$phosphor:regular/arrow-down$$', h: Down}
  - {t: '$$phosphor:regular/arrow-up$$', h: Up}
  - {t: '$$phosphor:regular/arrow-right$$', h: Right}
  - {t: '$$phosphor:regular/caret-line-up$$', h: Home}
  - {t: '$$phosphor:regular/caret-line-down$$', h: End}
  - {t: '$$phosphor:regular/arrow-fat-lines-up$$', h: SftCaps}
  - $$phosphor:regular/play-pause$$
  - $$phosphor:regular/speaker-slash$$
  - $$phosphor:regular/speaker-low$$
  - $$phosphor:regular/speaker-high$$
  - {t: '$$phosphor:regular/caret-double-up$$', h: PgUp}
  - ''
  - $$phosphor:regular/skip-forward$$
  - $$phosphor:regular/skip-back$$
  - {t: '$$phosphor:regular/sun$$', h: Up}
  - {t: '$$phosphor:regular/sun-dim$$', h: Down}
  - ''
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: MOUSE, h: toggle}
  - {t: SET, h: sticky}
  PROG:
  - '`'
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '0'
  - '-'
  - ESC
  - '!'
  - '@'
  - '#'
  - $
  - '%'
  - ^
  - '&'
  - '*'
  - (
  - )
  - '='
  - {t: '$$phosphor:regular/arrow-fat-lines-up$$', h: SftCaps}
  - {t: F20, h: '$$fa:brands/linux$$ LGui'}
  - F21
  - F22
  - F23
  - F24
  - ''
  - ','
  - .
  - '['
  - {t: ']', h: '$$fa:brands/linux$$ LGui'}
  - \
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - RCTL
  MOUSE:
  - {t: MOUSE, h: toggle}
  - ''
  - ''
  - {t: '$$phosphor:regular/mouse$$', h: '$$phosphor:regular/arrow-up$$'}
  - ''
  - ''
  - {t: '$$phosphor:regular/mouse-scroll$$', h: '$$phosphor:regular/arrow-down$$'}
  - {t: '$$phosphor:regular/mouse-scroll$$', h: '$$phosphor:regular/arrow-left$$'}
  - ''
  - ''
  - ''
  - ''
  - ESC
  - ''
  - {t: '$$phosphor:regular/mouse$$', h: '$$phosphor:regular/arrow-left$$'}
  - {t: '$$phosphor:regular/mouse$$', h: '$$phosphor:regular/arrow-down$$'}
  - {t: '$$phosphor:regular/mouse$$', h: '$$phosphor:regular/arrow-right$$'}
  - ''
  - {t: '$$phosphor:regular/mouse-scroll$$', h: '$$phosphor:regular/arrow-left$$'}
  - {t: '$$phosphor:regular/mouse-scroll$$', h: '$$phosphor:regular/arrow-down$$'}
  - {t: '$$phosphor:regular/mouse-scroll$$', h: '$$phosphor:regular/arrow-up$$'}
  - {t: '$$phosphor:regular/mouse-scroll$$', h: '$$phosphor:regular/arrow-right$$'}
  - ''
  - ''
  - {t: '$$mdi:apple-keyboard-control$$', h: LCtl}
  - ''
  - ''
  - ''
  - ''
  - ''
  - {t: '$$phosphor:regular/mouse-scroll$$', h: '$$phosphor:regular/arrow-up$$'}
  - {t: '$$phosphor:regular/mouse-scroll$$', h: '$$phosphor:regular/arrow-right$$'}
  - ''
  - ''
  - ''
  - {t: '$$phosphor:regular/key-return$$', h: RSHIFT}
  - ''
  - ''
  - $$phosphor:regular/mouse-left-click$$
  - $$phosphor:regular/mouse-right-click$$
  - $$phosphor:regular/mouse-scroll$$
  - ''
  SK:
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - ľ/Ľ
  - ú/Ú
  - ý/Ý
  - ä/Ä
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - á/Á
  - ŕ/Ŕ
  - š/Š
  - ť/Ť
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - ň/Ň
  - é/É
  - í/Í
  - ó/Ó
  - ô/Ô
  - {t: ▽, type: trans}
  - ž/Ž
  - {t: ▽, type: trans}
  - č/Č
  - ď/Ď
  - {t: ▽, type: trans}
  - €
  - £
  - ¥
  - ₹
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  NUMPAD:
  - {t: NUMPAD, h: toggle}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - LNLCK
  - KP 7
  - KP 8
  - KP 9
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - KP 4
  - KP 5
  - KP 6
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - KP 1
  - KP 2
  - KP 3
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - KP 0
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  SET:
  - ''
  - ''
  - {t: NUMPAD, h: toggle}
  - {t: QWERTY, h: toggle}
  - {t: GAM1, h: toggle}
  - {t: COLZY, h: toggle}
  - OUT TOG
  - ''
  - ''
  - ''
  - ''
  - ''
  - BT CLR
  - {t: '$$phosphor:regular/bluetooth$$', h: '0'}
  - {t: '$$phosphor:regular/bluetooth$$', h: '1'}
  - {t: '$$phosphor:regular/bluetooth$$', h: '2'}
  - {t: '$$phosphor:regular/bluetooth$$', h: '3'}
  - {t: '$$phosphor:regular/bluetooth$$', h: '4'}
  - {t: '$$phosphor:regular/bluetooth-slash$$', h: '0'}
  - {t: '$$phosphor:regular/bluetooth-slash$$', h: '1'}
  - {t: '$$phosphor:regular/bluetooth-slash$$', h: '2'}
  - {t: '$$phosphor:regular/bluetooth-slash$$', h: '3'}
  - {t: '$$phosphor:regular/bluetooth-slash$$', h: '4'}
  - $$phosphor:regular/power$$
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {t: '$$mdi:keyboard-close-outline$$', h: SoftOff}
  - ''
  - {type: held}
  - ''
  - ''
  - ''
  - {type: held}
